# Development Stage
FROM node:22-alpine AS dev

#Install git
RUN apk add --no-cache git

# Set working directory
WORKDIR /app

# Copy dependency manifests
COPY package*.json ./

# Install all dependencies including dev ones
RUN npm install

# Copy full source code
COPY . .

RUN cd node_modules ; ls -al; cd ..

# Expose the development port
EXPOSE 3000

# Default command for development (e.g., Vite, nodemon, etc.)
CMD ["npm", "run", "start"]
